<?php if ($this->showNotifications()) { ?>
    <?php if ($this->useDefaultStyles() || $this->getPosition()) { ?>
        <style type="text/css">
          
    <?php } ?>
<?php if ($this->useDefaultStyles()) { ?>
     
            #notification-bar #notification { width:950px; margin:0 auto; text-align:center; position:relative;  padding:16px 0px ;}
            #notification-bar span.close {cursor: pointer; position:absolute; right:0px; text-decoration: none; top:14px; }
            #notification-bar span.close img { vertical-align:middle;}
            #notification-bar .close a { text-decoration: none; color: #ffffff; }
            #notification-bar .close a:hover { text-decoration: none; }
             
    <?php } ?>
    <?php if ($this->getPosition()) { ?>
            <?php if ($this->getPosition() == 'bottom') { ?>
            #notification-bar.bottom { background: none repeat scroll 0 0 #C2C2C1; bottom: 0; color: #000; font-size: 12px;left: -2px; line-height:20px;opacity:0.9; filter:alpha(opacity=90); position: fixed; text-align: center; width: 100%; z-index: 1000;}
     <?php } ?>
        <?php if ($this->getPosition() == 'top') { ?>
                #notification-bar.top { position: fixed;top: 0; width: 100%; left:0px;z-index: 100; background: none repeat scroll 0 0 #C2C2C1;  color: #000; font-size: 12px; opacity:0.9; filter:alpha(opacity=90); / }
             body { margin-top: <?php echo $this->getBodyMargin() ?>; }
        <?php } 
        if($this->getPosition() == 'popup') {
            ?>
                        
                .bg-overlay{background:url(<?php echo $this->getSkinUrl('/notification/images/overlay.png') ?>) 0 0 repeat; height: 100%; left: 0; position: fixed; top: 0; width: 100%; z-index: 99;}
                .bg-overlay .center-align{ background: #FFFFFF; border: 5px solid #E5E4DD; left:0; top:0; margin: auto;  *margin: 20% auto 0 auto; position: absolute; *position: static; right: 0; bottom: 0; text-align: center;width: 645px; }
                .bg-overlay .center-align .pop-title{background: none repeat scroll 0 0 #F4F4F4; border-bottom: 1px solid #EBEBEB; font-size: 14px; font-weight: bold; padding:6px 15px; text-align:left;}
                .bg-overlay .center-align button{ *margin:0 3px;}
                .bg-overlay .center-align .popup-container { padding: 15px;}
                .bg-overlay .close{  background:url(<?php echo $this->getSkinUrl('/notification/images/closebox.png') ?>) 0 0 no-repeat; position: absolute; width: 30px; height: 30px; top:-18px; right:-18px; cursor:pointer;} 
            <?php
        }
    }
    ?>
    <?php if ($this->useDefaultStyles() || $this->getPosition()) { ?>
        </style>
    <?php } ?>
<?php } ?>

<script type="text/javascript">
    function popupwindow(w, h) {
        var left = (screen.width / 2) - (w / 2);
        var top = (screen.height / 2) - (h / 2);
        return window.open(url, title, 'toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=no, resizable=no, copyhistory=no, width=' + w + ', height=' + h + ', top=' + top + ', left=' + left);
    }
    popupwindow();
</script>
