<?php if ($this->showNotifications()): ?>
    <div class="bg-overlay">
        <?php
            $position = Mage::getStoreConfig('notification/notification_general/position');
            if ($position == 'top') {
            ?>
            <div id="notification-bar" class="top"><div id="notification"><span class="notification-content"><?php echo $this->getNotificationText(); ?></span><?php if ($this->closeNotification()) : ?>
                    <span class="close"><img src="<?php echo $this->getSkinUrl('notification/images/close-note.png') ?>" /></span><?php endif; ?></div></div>
            <?php }

            elseif ($position == 'bottom') {
            ?>
            <div id="notification-bar" class="bottom"><div id="notification"><span class="notification-content"><?php echo $this->getNotificationText(); ?></span><?php if ($this->closeNotification()) : ?><span class="close"><img src="<?php echo $this->getSkinUrl('notification/images/close-note.png') ?>" /></span><?php endif; ?></div></div>
            <?php }

            elseif ($position == 'popup') {
            ?>

            <div class="center-align">
                <div class="close"></div>
                <div class="pop-title">
                    <?php echo Mage::getStoreConfig('notification/notification_general/popup_title'); ?>
                </div>
                <div class="popup-container"><?php echo $this->getNotificationText(); ?></div>
            </div>


            <?php if (!$this->closeNotification()) : ?>
                <script type="text/javascript">
                    $$('.bg-overlay .close').first().observe('click', function(event) {
                            var callback = <?php echo ($this->getPosition() ? "function() { \$\$('body').first().setStyle({marginTop:0}); }" : "function(){}") ?>;
                            event.element().up('.bg-overlay').fade({duration: 0.5, afterFinish: callback});
                            Mage.Cookies.set("<?php echo $this->getNotificationClearCookieName() ?>", "1", new Date((new Date()).getTime() + 365 * 24 * 60 * 60 * 1000), "/");
                    });
                </script>
                <?php endif; ?>
            <script type="text/javascript">
                $$('.center-align')[0].style.height = $$('.pop-title')[0].clientHeight + $$('.popup-container')[0].clientHeight + 'px';
            </script>
            <?php } 
            elseif($this->getPosition() == 'leftcorner') { ?> 
            <div class="leftcorner-align">
                <div class="popup-container"><?php echo $this->getNotificationText(); ?></div>
                <?php if ($this->closeNotification()) : ?>
                    <div class="close">close</div>
                    <script type="text/javascript">
                        $$('.leftcorner-align .close').first().observe('click', function(event) {
                                event.element().up('.leftcorner-align').fade({duration: 0.5});
                                Mage.Cookies.set("<?php echo $this->getNotificationClearCookieName() ?>", "1", new Date((new Date()).getTime() + 365 * 24 * 60 * 60 * 1000), "/");
                        });
                    </script>
                    <?php endif; ?>
            </div>
            <?php  } 
            elseif($this->getPosition() == 'rightcorner') { ?> 
            <div class="rightcorner-align">
                <div class="popup-container"><?php echo $this->getNotificationText(); ?></div>
                <?php if ($this->closeNotification()) : ?>
                    <div class="close">close</div>
                    <script type="text/javascript">
                        $$('.rightcorner-align .close').first().observe('click', function(event) {
                                event.element().up('.bg-overlay').fade({duration: 0.5});
                                Mage.Cookies.set("<?php echo $this->getNotificationClearCookieName() ?>", "1", new Date((new Date()).getTime() + 365 * 24 * 60 * 60 * 1000), "/");
                        });
                    </script>
                    <?php endif; ?>
            </div>
            <?php  } ?>

    </div>
    <?php if ($this->closeNotification()) : ?>
        <script type="text/javascript">
            $$('.bg-overlay .close').first().observe('click', function(event) {
                    var callback = <?php echo ($this->getPosition() ? "function() { \$\$('body').first().setStyle({marginTop:0}); }" : "function(){}") ?>;
                    event.element().up('.bg-overlay').fade({duration: 0.5, afterFinish: callback});
                    Mage.Cookies.set("<?php echo $this->getNotificationClearCookieName() ?>", "1", new Date((new Date()).getTime() + 365 * 24 * 60 * 60 * 1000), "/");
            });
        </script>
        <?php endif; ?>
    <?php endif; ?>
   